use crate::config::{valid_name, Config};
use std::env;
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::os::unix::fs::OpenOptionsExt;
use std::path::{Path, PathBuf};

const MARKER: &str = "# Generated by appwarm. Edit ~/.config/appwarm/config instead.\n";

fn valid_desktop_id(id: &str) -> bool {
    id.ends_with(".desktop") && valid_name(id)
}

fn source(id: &str) -> io::Result<PathBuf> {
    let user = env::var("USER").map_err(io::Error::other)?;
    let mut roots = vec![format!("/etc/profiles/per-user/{user}/share")];
    roots.extend(
        env::var("XDG_DATA_DIRS")
            .unwrap_or_default()
            .split(':')
            .map(str::to_owned),
    );
    for root in roots {
        let path = Path::new(&root).join("applications").join(id);
        if path.is_file() {
            return Ok(path);
        }
    }
    Err(io::Error::new(
        io::ErrorKind::NotFound,
        format!("desktop entry {id} is unavailable"),
    ))
}

fn wrap_entry(text: &str, name: &str, binary: &Path) -> io::Result<String> {
    let binary = binary
        .to_str()
        .ok_or_else(|| io::Error::other("non-UTF-8 appwarm path"))?;
    let mut section = "";
    let mut replaced = false;
    let mut output = String::from(MARKER);
    for line in text.lines() {
        if line.starts_with('[') && line.ends_with(']') {
            section = line;
        }
        if section == "[Desktop Entry]" && line.starts_with("Exec=") {
            output.push_str(&format!("Exec={binary} desktop {name} -- {}\n", &line[5..]));
            replaced = true;
        } else {
            output.push_str(line);
            output.push('\n');
        }
    }
    if !replaced {
        return Err(io::Error::other("desktop entry has no main Exec line"));
    }
    Ok(output)
}

pub fn sync(cfg: &Config) -> io::Result<()> {
    let home = PathBuf::from(env::var_os("HOME").ok_or_else(|| io::Error::other("HOME is unset"))?);
    let data = env::var_os("XDG_DATA_HOME")
        .map(PathBuf::from)
        .filter(|path| path.is_absolute())
        .unwrap_or_else(|| home.join(".local/share"));
    let dest_dir = data.join("applications");
    fs::create_dir_all(&dest_dir)?;
    let binary = env::current_exe()?;
    for entry in &cfg.stages {
        let fields: Vec<_> = entry.split('|').collect();
        if fields.len() < 4 || !valid_name(fields[0]) || !valid_desktop_id(fields[2]) {
            eprintln!("appwarm: invalid desktop mapping: {entry}");
            continue;
        }
        let dest = dest_dir.join(fields[2]);
        if fs::symlink_metadata(&dest).is_ok()
            && (dest.is_symlink() || !fs::read_to_string(&dest)?.starts_with(MARKER))
        {
            eprintln!(
                "appwarm: leaving user-owned desktop entry {} untouched",
                dest.display()
            );
            continue;
        }
        let original = match source(fields[2]) {
            Ok(path) => path,
            Err(error) => {
                eprintln!("appwarm: {error}");
                continue;
            }
        };
        let content = wrap_entry(&fs::read_to_string(original)?, fields[0], &binary)?;
        let temp = dest.with_extension("desktop.appwarm-tmp");
        let mut file = OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .mode(0o644)
            .open(&temp)?;
        file.write_all(content.as_bytes())?;
        file.sync_all()?;
        fs::rename(temp, dest)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn replaces_only_main_exec() {
        let input = "[Desktop Entry]\nExec=zed %U\n[Desktop Action New]\nExec=zed --new %U\n";
        let output = wrap_entry(input, "zed", Path::new("/bin/appwarm")).unwrap();
        assert!(output.contains("Exec=/bin/appwarm desktop zed -- zed %U"));
        assert!(output.contains("[Desktop Action New]\nExec=zed --new %U"));
    }
}
